version: '3.7'
volumes:
  postgres-data:
  redis-data:
services:
  db:
    image: postgres
    #expose:
    #  - "5432"
    ports:
      - "5432:5432"
    volumes:
      # - ./tmp/db:/var/lib/postgresql/data
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - '.env'
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/worldzon-catalog-service
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    #links:
      # - elasticsearch
    #  - db
    #  - redis
    env_file:
      - '.env'
  sidekiq:
    build: .
    # command: 'bundle exec sidekiq'
    command: 'bundle exec sidekiq -C config/sidekiq.yml'
    volumes:
      - .:/worldzon-catalog-service
    environment:
      - '.env'
    #  RAILS_ENV: "docker_development"
    #  REDIS_URL: "redis://redis:6379/12"
    depends_on:
      - redis

